SBPRos2Driver:
  ros__parameters:
    interface: 3
    sbp_file: "/workspaces/Swift/24-185316.sbp"
    device_name: "/dev/ttyUSB0"
    connection_str: "115200|N|8|1|N"
    host_ip: "192.168.0.222"
    host_port: 55556
    read_timeout: 2000
    write_timeout: 2000
    frame_name: "swiftnav-gnss"
    timestamp_source_gnss: True
    enabled_publishers_ids: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]
    enabled_publishers_topics:
      [
        "angular_rate",
        "baseline_heading",
        "gnss_time_offset",
        "gpsfix",
        "imu_aux",
        "imu_raw",
        "navsatfix",
        "odometry",
        "orient_euler",
        "orient_quat",
        "timereference",
        "wheeltick",
        "posestamped"
      ]
    log_sbp_messages: False
    log_sbp_filepath: "/workspaces/Swift"
    baseline_dir_offset_deg: 0.0
    baseline_dip_offset_deg: 0.0
    track_update_min_speed_mps: 0.2

