SBPRos2Driver:
  ros__parameters:
    interface: 2
    sbp_file: "/workspaces/Swift/24-185316.sbp"
    device_name: "/dev/ttySAM3"
    connection_str: "115200|N|8|1|N"
    host_ip: "127.0.0.1"
    host_port: 55555
    read_timeout: 2000
    write_timeout: 2000
    navsatfix: True
    timereference: True
    log_sbp_messages: True
    log_sbp_filepath: "/workspaces/Swift"