name: CI

on:
  pull_request: ~
  push:
    branches:
      - 'master'
    tags:
      - 'v*'
      - '*.*.*'

name: SonarCloud
jobs:
  sonarcloud:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN_AUTO }}
        with:
          args: >
            -Dsonar.organization=swift-nav
            -Dsonar.projectKey=swiftnav-ros2
            -Dsonar.sources=.
            -Dsonar.exclusions=java/**
            -Dsonar.verbose=true
            -Dsonar.c.file.suffixes=- -Dsonar.cpp.file.suffixes=-
